# Generated by Django 4.1.9 on 2023-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=255)),
                ("make_again", models.CharField(max_length=10)),
                ("recipe", models.TextField()),
                ("rating", models.IntegerField()),
                ("notes", models.TextField()),
            ],
        ),
    ]
